### ISSUE TITLE
Calls not received in App closed when calling from GSM in PL

### ISSUE THREAD

**Issue by rodrigomonelos** [saycel/webph.one#119]

**Comment by rodrigomonelos** [comment]
This one is in progress, waiting for @Tcat1 to make the tests, isn't it?

**Comment by rodrigomonelos** [comment]
Bloqued until backhaul is repaired after lightning strike

**Comment by Tcat1** [comment]
So we Have now Got Backhaul Working. I have made initial test and GSM to App is not working properly. I will be posting here a link to video and a Report For Everyone over the next 24hrs...

**Comment by Tcat1** [comment]
Bug report
Structure template
Title: Dialing From GSM Pearl Cel SIM to App 
Description: since some time ago (not always), when trying to call app from a GSM Pearl Cel SIM the App is not receiving call in proper manner.
Expected result: Dial App from a GSM Pearl Cel Dumb Phone and App Rings in backgorund or allows option to pick up call
Obtained result: When calling App from GSM Pearl Cel Dumb Phone and app is not open call does not go through. When App is open call will go through but does not give proper option for answering call on the app side. VIEW VIDEO FOR EXAMPLE
Steps to reproduce: [relevant steps before the result] 
Call App From a Pearl Cel SIM
Have App Not Open on Your SmartPhone
Try With App open on Your Smartphone
Suggested priority: [use the available tags: high, medium, low] High
Video, screenshots
https://www.youtube.com/watch?v=ZA5ZDcRDcB0

https://www.youtube.com/watch?v=H5hk06VRvFk
Context
Device: happens both from Hauwai and Samsung J2
OS and version: Android 6.0.1 and Android 5.1.1
Browser and version: Chrome 61.0.3163.98 (Phone))
App version: [get the code by dialing 000000] SayCel develop - HEAD - 4e7f23e
Other relevant info: … This Has been Occurring Since Release

**Comment by gmarcos87** [comment]
Call not play sound: Chrome 61 change the policy about audio player via Javascirpt. See more in https://developers.google.com/web/updates/2017/09/autoplay-policy-changes, they are not yet a workarround for this. We can no longer ring the pwa phone at our wish.
Not from the web, but if when the app is installed. Can you perform the tests with this modality? Apparently chrome is handling security schemes increasingly different if the apps are installed.

**Comment by rodrigomonelos** [comment]
Ok, so if I understand, @Tcat1 should make the test but with the app previously added to home screen, is that right @gmarcos87?

**Comment by gmarcos87** [comment]
Yes

El 15 nov. 2017 2:08 p. m., "rodrigomonelos" <notifications@github.com>
escribió:

Ok, so if I understand, @Tcat1 <https://github.com/tcat1> should make the
test but with the app previously added to home screen, is that right
@gmarcos87 <https://github.com/gmarcos87>?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/saycel/webph.one/issues/119#issuecomment-344660772>,
or mute
the thread

**Comment by Tcat1** [comment]
Yes I did make test with app downloaded to home screen but same results

**Comment by rodrigomonelos** [comment]
@gmarcos87 Can yoy give priority to this issue? This is now the only relevant isue we see towards the  release. Do you need help from someone to work on it?

**Comment by rodrigomonelos** [comment]
Ok so if I'm getting it right, we have here two issues. One is related with the backend registering that the user is offline and the other is related with the app showing the options to anser.
I suggest we to close the current issue and follow up on this two new ones

- Number is presented as "busy" up to 1' after call #131 
- Show options for answering the call #133

Do you agree @gmarcos87 @Tcat1 ? Do you think we're missing something?
